# before_install
# install - install any dependencies required
install:
  - uname -a
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo dpkg -i hugo_*.deb
  - hugo version

before_script:
  - rm -rf public 2> /dev/null

# script - run the build script
script:
  - hugo 2> /dev/null

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure
  committer_from_gh: true
  verbose: true
  keep_history: true
  local_dir: public
  target_branch: master
  on:
    branch: source
